name: Draft release
on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
